import os

EMBED_REMORT_NGROK_API_ENDPOINT = os.getenv("EMBED_REMORT_NGROK_API_ENDPOINT")
EMBED_REMORT_CLOUDFLARED_API_ENDPOINT = os.getenv("EMBED_REMORT_CLOUDFLARED_API_ENDPOINT")

ENDPOINTS = {
    "ngrok": EMBED_REMORT_NGROK_API_ENDPOINT,
    "cloudflared": EMBED_REMORT_CLOUDFLARED_API_ENDPOINT,
}